title: Computer System Conference Deadlines # (Maintained by @samuelgong)
# email: zjiangaj@cse.ust.hk
description: Countdowns to computer system conference deadlines
author: Zhifeng Jiang

domain: "samuelgong.github.io"
baseurl: ""

github_username: samuelgong
github_repo: sys-deadlines
twitter_username: Zhifeng_jiang
twitter_hashtag: system

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
theme: jekyll-theme-cayman
